# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: balbader <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/26 14:46:37 by balbader          #+#    #+#              #
#    Updated: 2020/09/27 18:51:52 by balbader         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = display_file

SRC = ft_display_file.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
